
pool:
  vmImage: 'windows-2019'
jobs:
- job: Windows

  steps:
  - task: CmdLine@2
    inputs:
      script: 'systeminfo | findstr /B /C:"OS Name" /C:"OS Version" /C:"System Type"'
  - task: CmdLine@2
  
    displayName: Chrome Test on Windows
    inputs:
      script: 'gradlew.bat clean test aggregate reports --info -Pos=windows -Pdriver=chrome'
  - task: CmdLine@2
    displayName: Firefox Test on Windows
    inputs:
      script: 'gradlew.bat clean test aggregate reports --info -Pos=windows -Pdriver=firefox'
  - task: CmdLine@2
    displayName: Edge Test on Windows
    inputs:
      script: 'gradlew.bat clean test aggregate reports --info -Pos=windows -Pdriver=edge'

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: CmdLine@2
    displayName: Setting executable permissions
    inputs:
      script: |
        chmod +x gradle-env-wrapper-linux

        chmod +x src/test/resources/webdriver/linux/chromedriver-linux64/chromedriver
        
        chmod +x src/test/resources/jdks/linux/bin/*
  - task: CmdLine@2
    displayName: Chrome Test on Linux
    inputs:
      script: './gradle-env-wrapper-linux clean test aggregate reports --info -Pos=linux -Pdriver=chrome'
  - task: CmdLine@2
    displayName: Firefox test on Linux
    inputs:
      script: './gradle-env-wrapper-linux clean test aggregate reports --info -Pos=linux -Pdriver=firefox'
  - task: CmdLine@2
    displayName: Edge test on Linux
    inputs:
      script: './gradle-env-wrapper-linux clean test aggregate reports --info -Pos=linux -Pdriver=edge'
