#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

JAVA_HOME="/usr/lib/jvm/temurin-21-jdk-amd64"
export JAVA_HOME
export PATH="$JAVA_HOME/bin:$PATH"

export GRADLE_USER_HOME="${AGENT_TEMPDIRECTORY:-${RUNNER_TEMP}}/gradle"
mkdir -p "$GRADLE_USER_HOME"

#export JAVA_HOME="$SCRIPT_DIR/src/test/resources/jdks/linux"
#export PATH="$JAVA_HOME/bin:$PATH"

echo "DEBUG: JAVA_HOME is set to $JAVA_HOME"
echo "DEBUG: Which java: $(which java)"
java -version

chmod +x "$SCRIPT_DIR/gradlew"
chmod +x src/test/resources/webdriver/linux/chromedriver-linux64/chromedriver
chmod +x src/test/resources/webdriver/linux/edgedriver-linux64/msedgedriver
chmod +x src/test/resources/webdriver/linux/geckodriver-linux64/geckodriver

"$SCRIPT_DIR/gradlew" "$@"
