#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

export JAVA_HOME="$SCRIPT_DIR/src/test/resources/jdks/mac/Contents/Home"
export PATH="$JAVA_HOME/bin:$PATH"

echo "DEBUG: JAVA_HOME is set to $JAVA_HOME"
echo "DEBUG: Which java: $(which java)"
java -version

chmod +x "$SCRIPT_DIR/gradlew"
#sudo chmod -R 755 Baseline-Automation-Framework

"$SCRIPT_DIR/gradlew" "$@" --scan
